// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzJblR6leiYwiWDVPjbr2-L3jf3qdOMLU',
    appId: '1:433837086385:web:a757ce1e12c8e43418b490',
    messagingSenderId: '433837086385',
    projectId: 'taller-firebase-universi-78464',
    authDomain: 'taller-firebase-universi-78464.firebaseapp.com',
    storageBucket: 'taller-firebase-universi-78464.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl7ikc6nLJFFFDCaifMg4U_1chaX5WGuU',
    appId: '1:433837086385:android:e06fba95037a3f3a18b490',
    messagingSenderId: '433837086385',
    projectId: 'taller-firebase-universi-78464',
    storageBucket: 'taller-firebase-universi-78464.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmA86B6C6osTbvDu_RriqmSOy0DAm6yC8',
    appId: '1:433837086385:ios:4dc208cf4c12197718b490',
    messagingSenderId: '433837086385',
    projectId: 'taller-firebase-universi-78464',
    storageBucket: 'taller-firebase-universi-78464.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmA86B6C6osTbvDu_RriqmSOy0DAm6yC8',
    appId: '1:433837086385:ios:4dc208cf4c12197718b490',
    messagingSenderId: '433837086385',
    projectId: 'taller-firebase-universi-78464',
    storageBucket: 'taller-firebase-universi-78464.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzJblR6leiYwiWDVPjbr2-L3jf3qdOMLU',
    appId: '1:433837086385:web:a4c5a6cae2447f3a18b490',
    messagingSenderId: '433837086385',
    projectId: 'taller-firebase-universi-78464',
    authDomain: 'taller-firebase-universi-78464.firebaseapp.com',
    storageBucket: 'taller-firebase-universi-78464.firebasestorage.app',
  );
}
